version: '3.4'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
#    build:
#      context: .
#      dockerfile: db/dockerfile
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "masterkey"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
#   volumes:
#      - C:\meusvolumes\volumes\sqlserver:/var/opt/mssql/data
  rest-with-aspnet:
    image: rest-with-aspnet
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "masterkey"
      Database: "peopledb"
    ports:
      - 44300:80
    depends_on:
      - mssql-server
    networks:
      - asp-network
networks:
  asp-network:
    driver: bridge