version: '3.4'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "peoPle_db23*$"
    ports:
      - "1433:1433"
  rest-with-aspnet:
    image: rest-with-aspnet
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "peoPle_db23*$"
      Database: "peopledb"
    ports:
      - 44300:80